[[redirects]]
  from = "/api/*"
  to = "https://hcsb.synology.me:6555/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200